# Generated by Django 4.1.2 on 2022-10-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hp', models.IntegerField(default=100)),
                ('attack', models.IntegerField(default=5)),
                ('defence', models.IntegerField(default=5)),
                ('backstory', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='HeroRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.IntegerField(choices=[(0, 'Human'), (1, 'Elf'), (2, 'Dwarf')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hp', models.IntegerField(default=100)),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonsterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_type', models.IntegerField(choices=[(0, 'Human'), (1, 'Wildlife'), (2, 'Undead')], default=0)),
            ],
        ),
    ]
