# Generated by Django 4.1.2 on 2022-10-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='monster_type',
            field=models.IntegerField(choices=[(0, 'Human'), (1, 'Wildlife'), (2, 'Undead')], default=0),
        ),
    ]
