# Generated by Django 4.1.2 on 2022-10-16 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentEventInJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('day_visited', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='journal',
            name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.AddField(
            model_name='journey',
            name='event',
            field=models.ManyToManyField(through='AGONy.CurrentEventInJourney', to='AGONy.event'),
        ),
        migrations.AddField(
            model_name='journey',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGONy.hero'),
        ),
        migrations.AddField(
            model_name='currenteventinjourney',
            name='current_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGONy.event'),
        ),
        migrations.AddField(
            model_name='currenteventinjourney',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGONy.journey'),
        ),
    ]
