# Generated by Django 4.1.2 on 2022-10-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0002_currenteventinjourney_journey_remove_journal_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currenteventinjourney',
            old_name='current_event',
            new_name='event',
        ),
    ]
