# Generated by Django 4.1.2 on 2022-10-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0002_monster_monster_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroRace',
        ),
        migrations.DeleteModel(
            name='MonsterType',
        ),
        migrations.AddField(
            model_name='hero',
            name='race',
            field=models.IntegerField(choices=[(0, 'Human'), (1, 'Elf'), (2, 'Dwarf')], default=0),
        ),
        migrations.AddField(
            model_name='monster',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='monster_level',
            field=models.IntegerField(choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], default=0),
        ),
    ]
