# Generated by Django 4.1.2 on 2022-10-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0003_delete_herorace_delete_monstertype_hero_race_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='gold',
            field=models.IntegerField(default=0),
        ),
    ]
