# Generated by Django 4.1.2 on 2022-10-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0003_rename_current_event_currenteventinjourney_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=7),
        ),
        migrations.CreateModel(
            name='CurrentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGONy.event')),
            ],
        ),
    ]
