# Generated by Django 4.1.2 on 2022-10-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0004_hero_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=10),
        ),
    ]
