# Generated by Django 4.1.2 on 2022-10-16 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0004_alter_monster_monsters_gold_currentevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenteventinjourney',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGONy.currentevent'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='event',
            field=models.ManyToManyField(through='AGONy.CurrentEventInJourney', to='AGONy.currentevent'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=9),
        ),
    ]
