# Generated by Django 4.1.3 on 2023-01-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0005_remove_monster_monster_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=9),
        ),
    ]
