# Generated by Django 4.1.2 on 2022-10-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0005_alter_currenteventinjourney_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=10),
        ),
    ]
