# Generated by Django 4.1.2 on 2022-10-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0006_alter_monster_monsters_gold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='event_type',
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=6),
        ),
    ]
