# Generated by Django 4.1.2 on 2022-10-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0006_alter_monster_monsters_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='attack',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='monster',
            name='defence',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='monster',
            name='hp',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=8),
        ),
    ]
