# Generated by Django 4.1.3 on 2023-01-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0006_alter_monster_monsters_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsteraidescription',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=8),
        ),
    ]
