# Generated by Django 4.1.3 on 2023-01-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0007_monsteraidescription_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=10),
        ),
    ]
