# Generated by Django 4.1.2 on 2022-10-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0007_alter_monster_attack_alter_monster_defence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliveMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AliveMonsterInStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGONy.alivemonster')),
            ],
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=9),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('visited', models.BooleanField(default=False)),
                ('monsters', models.ManyToManyField(through='AGONy.AliveMonsterInStage', to='AGONy.alivemonster')),
                ('next_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='AGONy.stage')),
            ],
        ),
        migrations.AddField(
            model_name='alivemonsterinstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGONy.stage'),
        ),
        migrations.AddField(
            model_name='alivemonster',
            name='monster_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGONy.monster'),
        ),
    ]
