# Generated by Django 4.1.3 on 2023-01-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0008_monsterimage_name_alter_monster_monsters_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monster_monster_image',
            field=models.ManyToManyField(blank=True, null=True, through='AGONy.MonsterMonsterImage', to='AGONy.monsterimage'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=8),
        ),
    ]
