# Generated by Django 4.1.2 on 2022-10-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0008_journey_next_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=5),
        ),
    ]
