# Generated by Django 4.1.2 on 2022-10-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0009_event_stage_hero_alter_monster_monsters_gold_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=10),
        ),
    ]
