# Generated by Django 4.1.3 on 2023-01-13 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0009_alter_monster_monster_monster_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAIDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_AI_description', models.TextField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/uploaded')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Event', max_length=100),
        ),
        migrations.CreateModel(
            name='EventEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGONy.event')),
                ('monster_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGONy.eventimage')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_AI_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AGONy.eventaidescription'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_event_image',
            field=models.ManyToManyField(blank=True, null=True, through='AGONy.EventEventImage', to='AGONy.eventimage'),
        ),
    ]
