# Generated by Django 4.1.2 on 2022-10-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0010_alter_monster_monsters_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_type', models.IntegerField(choices=[(0, 'General'), (1, 'Racial'), (2, 'TragicOrgin')], default=0)),
                ('origin_description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=8),
        ),
    ]
