# Generated by Django 4.1.2 on 2022-10-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0011_origin_alter_monster_monsters_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='origin',
            name='origin_type',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'TragicOrigin'), (2, 'Racial')], default=0),
        ),
    ]
