# Generated by Django 4.1.2 on 2022-10-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0015_alter_monster_monsters_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(0, 'Monster Encounter'), (1, 'Loot Encounter'), (2, 'Trap Encounter'), (3, 'Empty Encounter')], default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='stage',
            name='level',
            field=models.IntegerField(),
        ),
    ]
