# Generated by Django 4.1.2 on 2022-10-13 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0016_alter_event_type_alter_monster_monsters_gold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='stage',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGONy.hero'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGONy.hero')),
            ],
        ),
    ]
