# Generated by Django 4.1.2 on 2022-10-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0018_alter_monster_monsters_gold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='next_stage',
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=9),
        ),
    ]
