# Generated by Django 4.1.2 on 2022-10-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0019_remove_stage_next_stage_alter_monster_monsters_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=7),
        ),
    ]
