# Generated by Django 4.1.2 on 2022-10-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0020_alter_monster_monsters_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='stage',
            name='monsters',
            field=models.ManyToManyField(null=True, through='AGONy.AliveMonsterInStage', to='AGONy.alivemonster'),
        ),
    ]
