# Generated by Django 4.1.2 on 2022-10-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0022_alter_monster_monsters_gold_alter_stage_monsters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=7),
        ),
    ]
