# Generated by Django 4.1.2 on 2022-10-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0023_alter_monster_monsters_gold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='hero',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='monster',
            name='monsters_gold',
            field=models.IntegerField(default=8),
        ),
    ]
