# Generated by Django 4.1.2 on 2022-10-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AGONy', '0027_alivemonsterinstagex_alter_monster_monsters_gold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagex',
            name='game',
        ),
        migrations.RemoveField(
            model_name='stagex',
            name='monsters',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='game',
            new_name='hero',
        ),
        migrations.DeleteModel(
            name='AliveMonsterInStagex',
        ),
        migrations.DeleteModel(
            name='Stagex',
        ),
    ]
